[[repositories]]
repository_folder = "repos_charts/istio"
chart_folder_path = "manifests/charts/base"

[[repositories]]
repository_folder = "repos_charts/helm-charts"
chart_folder_path = "charts/alertmanager"