name: Helm Chart Practice Evolution Analysis

on:
  push:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout TON repo d'analyse
      - name: Checkout analysis repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 3️⃣ Install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib python-dateutil tomli pyyaml pandas

      # 4️⃣ Clean workspace
      - name: Clean workspace
        run: |
          rm -rf target-repo
          mkdir target-repo
          rm -rf graphs_practices_over_time
          mkdir graphs_practices_over_time


      # 5️⃣ Clone Helm repository
      - name: Clone Helm repository
        run: |
          REPO_URL=$(python - <<EOF
          import tomli
          with open("graph-analyze-practice.toml", "rb") as f:
              print(tomli.load(f)["repository"]["repo_url"])
          EOF
          )
          git clone "$REPO_URL" target-repo

      # # global analysis script for latest info in the csv file
      # - name: Prepare analysis script
      #   run: |
      #     python code_smells_calculator.py 

      # 6️⃣ Run analysis
      - name: Run practice evolution analysis
        run: |
          python generate_practice_evolution.py

      # 7️⃣ Upload graphs as artifacts
      - name: Upload graphs
        uses: actions/upload-artifact@v4
        with:
          name: helm-practice-evolution-graphs
          path: graphs_practices_over_time/
